- name: Restart Caddy
  systemd:
    name: caddy
    state: restarted
    daemon_reload: yes
  listen: "reload caddy"
  when: caddy_admin_off | default(true)

- name: Reload Caddy
  systemd:
    name: caddy
    state: reloaded
  listen: "reload caddy"
  when: not caddy_admin_off | default(true) | bool
