# SAMPLE Group: proxy_group
# Copy this to ansible/group_vars/<your_group_name>.yml and customize

cloudflare_api_token: "YOUR_CLOUDFLARE_API_TOKEN"

# List of sites to proxy for this group
caddy_sites:
  - domain:
      - example.com
      - www.example.com
    upstream: 10.0.0.10:80

  - domain: "api.example.com"
    upstreams:
      - path: "/v1/*"
        target: 10.0.0.11:8000
    default_response: "API Root"

  - domain: "secure.example.com"
    upstream: https://10.0.0.12:443
    skip_upstream_cert_verify: true
